### ISSUE TITLE
Getting error while authorizing using blogid

### ISSUE THREAD

**Issue by potholiday** [raghur/easyblogger#1]
So I am new to your module and I find it fascinating and easy comparing to Google's own blogger API module. My computer is ubuntu 14.04 and python 2.7

I have installed your program and its requirement pandoc by this way

```
sudo pip install EasyBlogger
sudo apt-get install pandoc
```

But when I tried to get authorized using your method

```
sudo easyblogger --blogid <yourblogid> get
```

its showing this error

```
 File "/usr/local/bin/easyblogger", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_res
```

I even tried your blogid `sudo easyblogger --blogid 7642453 get` but I am getting the same error

**Comment by raghur** [comment]
@potholiday I'm not able to reproduce the issue.. I'm testing with a docker container with python 2.7. Also your error message seems to be cut off - can you paste the entire message? 

```
bash-4.3# python --version
Python 2.7.13

bash-4.3# pip list
EasyBlogger (0.9.5)
google-api-python-client (1.6.1)
httplib2 (0.9.2)
oauth2client (4.0.0)
pip (9.0.1)
....

bash-4.3# easyblogger --blogid 7642453  get                                                                                                         
/usr/lib/python2.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /root/.easyblogger.credentials: No such file or directory 
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))                                                                                             
                                                                                                                                                    
Your browser has been opened to visit:                                                                                                              
...
```

**Comment by potholiday** [comment]
This is the full error 

```
Traceback (most recent call last):
  File "/usr/local/bin/easyblogger", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (httplib2 0.8 (/usr/lib/python2.7/dist-packages), Requirement.parse('httplib2<1dev,>=0.9.2'), set(['google-api-python-client']))

```

**Comment by raghur** [comment]
Looks like httplib2 min version required is 0.9.2 but it can find only   0.8. can you try upgrading it?

**Comment by potholiday** [comment]
I have tried to update httplib2 using `sudo pip install httplib2` but its showing ` InsecurePlatformWarning` error. I may have to install directly it from the github itself. Any way thanks for solving my problem.
