### ISSUE TITLE
Error in Creating New Post from a File

### ISSUE THREAD

**Issue by KarthikAbiram** [raghur/easyblogger#105]
Hi,

First I would like to thank you for creating this nice tool!

I was able to set things up and able to export an existing post to a file in markdown format using the below command:
**easyblogger --blogid 4722945922612222558 get -p 3418532693618783118 -d markdown --write-files**

I am facing an issue when trying to create/update a post from file. I used the below command:
**easyblogger --blogid 4722945922612222558 file this-is-my-post-title.markdown**

I got the below error, which I am not sure how to resolve. Any help or pointers regarding this is greatly appreciated. Thanks!

**Error Details**
_C:\Users\maze\AppData\Local\Temp\tmp9ds2cgzw.adoc
'asciidoctor' is not recognized as an internal or external command,
operable program or batch file.
Command '['asciidoctor', '-v', '-r', 'asciidoctor-diagram', '-a', 'stylesheet!', '-a', 'allow-uri-read', '-a', 'sectanchors', '-a', 'sectnums', '-a', 'last-update-label!', '-a', 'experimental', '-a', 'data-uri', '-a', 'icons=font', 'C:\\Users\\maze\\AppData\\Local\\Temp\\tmp9ds2cgzw.adoc']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "c:\users\maze\appdata\local\programs\python\python37-32\lib\site-packages\blogger\main.py", line 328, in processItem
    publishDate=args.publishDate)
  File "c:\users\maze\appdata\local\programs\python\python37-32\lib\site-packages\blogger\blogger.py", line 273, in updatePost
    blogPost['content'] = self._getMarkup(content, fmt, filters)
  File "c:\users\maze\appdata\local\programs\python\python37-32\lib\site-packages\blogger\blogger.py", line 231, in _getMarkup
    raise e
  File "c:\users\maze\appdata\local\programs\python\python37-32\lib\site-packages\blogger\blogger.py", line 225, in _getMarkup
    self.check_output(cmd, shell=True)
  File "c:\users\maze\appdata\local\programs\python\python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\users\maze\appdata\local\programs\python\python37-32\lib\site-packages\gevent\subprocess.py", line 1686, in run
    raise _with_stdout_stderr(CalledProcessError(retcode, process.args, stdout), stderr)
subprocess.CalledProcessError: Command '['asciidoctor', '-v', '-r', 'asciidoctor-diagram', '-a', 'stylesheet!', '-a', 'allow-uri-read', '-a', 'sectanchors', '-a', 'sectnums', '-a', 'last-update-label!', '-a', 'experimental', '-a', 'data-uri', '-a', 'icons=font', 'C:\\Users\\maze\\AppData\\Local\\Temp\\tmp9ds2cgzw.adoc']' returned non-zero exit status 1.
2019-12-11T16:27:42Z <Greenlet at 0x42a3c90: processItem(Namespace(blogid='4722945922612222558', clientid=', <blogger.blogger.ContentArgParser object at 0x03AF)> failed with CalledProcessError_

**Comment by KarthikAbiram** [comment]
I switched to Python 3.6 and tried, but got the same error there as well. Any help is appreciated!
**Command:**
easyblogger --blogid 4722945922612222558 file this-is-my-post-title.markdown

**Error Details:**
c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\blogger.py:344: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  frontmatter = yaml.load(isYaml[0][3])
C:\Users\maze\AppData\Local\Temp\tmpoya6le26.adoc
'asciidoctor' is not recognized as an internal or external command,
operable program or batch file.
Command '['asciidoctor', '-v', '-r', 'asciidoctor-diagram', '-a', 'stylesheet!', '-a', 'allow-uri-read', '-a', 'sectanchors', '-a', 'sectnums', '-a', 'last-update-label!', '-a', 'experimental', '-a', 'data-uri', '-a', 'icons=font', 'C:\\Users\\maze\\AppData\\Local\\Temp\\tmpoya6le26.adoc']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\main.py", line 328, in processItem
    publishDate=args.publishDate)
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\blogger.py", line 273, in updatePost
    blogPost['content'] = self._getMarkup(content, fmt, filters)
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\blogger.py", line 231, in _getMarkup
    raise e
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\blogger.py", line 225, in _getMarkup
    self.check_output(cmd, shell=True)
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\gevent\subprocess.py", line 1686, in run
    raise _with_stdout_stderr(CalledProcessError(retcode, process.args, stdout), stderr)
subprocess.CalledProcessError: Command '['asciidoctor', '-v', '-r', 'asciidoctor-diagram', '-a', 'stylesheet!', '-a', 'allow-uri-read', '-a', 'sectanchors', '-a', 'sectnums', '-a', 'last-update-label!', '-a', 'experimental', '-a', 'data-uri', '-a', 'icons=font', 'C:\\Users\\maze\\AppData\\Local\\Temp\\tmpoya6le26.adoc']' returned non-zero exit status 1.
2019-12-12T04:35:57Z <Greenlet at 0x47bdb58: processItem(Namespace(blogid='4722945922612222558', clientid=', <blogger.blogger.ContentArgParser object at 0x0405)> failed with CalledProcessError

**Comment by raghur** [comment]
> 'asciidoctor' is not recognized as an internal or external command,
operable program or batch file.
Command '['asciidoctor', '-v', '-r', 'asciidoctor-diagram', '-a', 'stylesheet!', '-a', 'allow-uri-read', '-a', 'sectanchors', '-a', 'sectnums', '-a', 'last-update-label!', '-a', 'experimental', '-a', 'data-uri', '-a', 'icons=font', 'C:\Users\maze\AppData\Local\Temp\tmp9ds2cgzw.adoc']' returned non-zero exit status 

Looks like `easyblogger` thinks its asciidoc format and tries to use asciidoctor which you don't have installed. Can you post the frontmatter in your file `this-is-my-post-title.markdown`

Keep in mind that the frontmatter in each markdown/asciidoc file is what drives processing and metadata picked up easyblogger

**Comment by KarthikAbiram** [comment]
Thank you for your quick response. 

The file was generated using EasyBlogger command:
easyblogger --blogid 4722945922612222558 get -p 3418532693618783118 -d markdown --write-files

The frontmatter of the file "this-is-my-post-title.markdown" is:

**Comment by raghur** [comment]
add `format	 : markdown` to your frontmatter. Do go through the README will help (yes - its long - but you can just jump to stuff that is of interest)

**Comment by KarthikAbiram** [comment]
Thanks Raghu!

I earlier tried the frontmatter format provided in ReadMe which resulted in an error. The error that I got earlier was:

c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\blogger.py:344: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  frontmatter = yaml.load(isYaml[0][3])
Traceback (most recent call last):
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\maze\AppData\Local\Programs\Python\Python36-32\Scripts\easyblogger.exe\__main__.py", line 9, in <module>
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\main.py", line 291, in main
    return runner(args)
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\main.py", line 372, in runner
    contentArgs.updateArgs(argsCopy)
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\blogger.py", line 412, in updateArgs
    self._inferArgsFromContent()
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\blogger\blogger.py", line 344, in _inferArgsFromContent
    frontmatter = yaml.load(isYaml[0][3])
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "c:\users\maze\appdata\local\programs\python\python36-32\lib\site-packages\yaml\scanner.py", line 260, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 5, column 7:
    format       : markdown

Looks like there is a tab space after "format" which needs to be removed. Kindly update the readme section.

I am now able to get it to work. I am attaching a sample format here for others to refer - 
[PostFormat.md.txt](https://github.com/raghur/easyblogger/files/3955048/PostFormat.md.txt)

I understand that there are multiple frontmatter formats and keys supported. If possible, please add a sample file for the most common/popular formats directly as files in git, which will make it easy for others to refer.

Thanks a lot for all the help!
