### ISSUE TITLE
UnicodeDecodeError when using German Umlaut from Windows Commandline

### ISSUE THREAD

**Issue by schmonet** [raghur/easyblogger#13]
Hi, 

thanks a lot for this great CMD-blogging-script :-)
When i use German Umlaute like **"ü,ä,ö"** for uploading a new post from a Win 10 Commandline (or batch), i get the Error:
**UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 0: invalid start byte**

I tired to Escape "ü" to "&uuml;", but this will not work for the Labels (In Blogger the Post-Text will be displayed korrektly but the labels will display the escaping).

Am i doing something wrong?

C:\Users\xxx>easyblogger --blogid "xxx" post -t "ü" -l "ü" -c "ü" --publish
Traceback (most recent call last):
  File "c:\program files (x86)\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\program files (x86)\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Program Files (x86)\Python27\Scripts\easyblogger.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\blogger\main.py", line 246, in main
    return runner(args)
  File "c:\program files (x86)\python27\lib\site-packages\blogger\main.py", line 328, in runner
    return processItem(args)
  File "c:\program files (x86)\python27\lib\site-packages\blogger\main.py", line 259, in processItem
    fmt=args.format)
  File "c:\program files (x86)\python27\lib\site-packages\blogger\blogger.py", line 245, in post
    isDraft=isDraft)
  File "c:\program files (x86)\python27\lib\site-packages\googleapiclient\discovery.py", line 790, in method
    actual_path_params, actual_query_params, body_value)
  File "c:\program files (x86)\python27\lib\site-packages\googleapiclient\model.py", line 151, in request
    body_value = self.serialize(body_value)
  File "c:\program files (x86)\python27\lib\site-packages\googleapiclient\model.py", line 260, in serialize
    return json.dumps(body_value)
  File "c:\program files (x86)\python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "c:\program files (x86)\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\program files (x86)\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 0: invalid start byte

Thanks!

**Comment by raghur** [comment]
I just tried this `easyblogger post -t "ü" -l "ü" -c "ü" --publish` on my machine - worked fine - though I'm using python3 and you're on python2

I'll try to test this with py2

**Comment by schmonet** [comment]
WORKS under Python 27 in my Win10-Console! Great! Many thanks for this quick fix :-)
Upgrading to python3 would have been also be an option for me - simply didnt know this.
P.S: Do you plan to implement more options from the Blogger API? I am especially interested in setting an explizit publish-date manually, to "pre-post" historical Storys to the date, they actally happened?!
Thanks again!
