### ISSUE TITLE
RuntimeError: Pandoc died with exitcode "83" during conversion

### ISSUE THREAD

**Issue by qijianjun** [raghur/easyblogger#43]
I install easyblogger and run it under msys2 env, but encounter the following error, have no idea after google, seems to be related with greentlet or filters.

```
$ /C/Python34/Scripts/easyblogger file test.md
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "c:\python34\lib\site-packages\blogger\main.py", line 306, in processItem
    publishDate=args.publishDate)
  File "c:\python34\lib\site-packages\blogger\blogger.py", line 243, in post
    markup = self._getMarkup(content, fmt, filters)
  File "c:\python34\lib\site-packages\blogger\blogger.py", line 234, in _getMarkup
    raw, 'html', format=fmt, filters=filters)
  File "c:\python34\lib\site-packages\pypandoc\__init__.py", line 69, in convert
    outputfile=outputfile, filters=filters)
  File "c:\python34\lib\site-packages\pypandoc\__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "83" during conversion: b'Error running filter <path:\r\nCould not find executable <path\r\n'
2018-09-08T06:06:18Z <Greenlet "Greenlet-0" at 0x5929848: processItem(Namespace(blogid='6585907284031683011', clientid=', <blogger.blogger.ContentArgParser object at 0x0000)> failed with RuntimeError
```

**Comment by raghur** [comment]
can you post contents of test.md? Looks like there's a filter configured and pandoc has trouble finding the filter.

**Comment by qijianjun** [comment]
I have no idea about the filter, so leave it as the example.

```
<!--
id:
title    : TEST
labels   : [tag1, tag2, tag3]
format   : markdown
published: false
PublishDate: 2018-09-10T10:00:00
filters: <path to your filter>
-->
## Title
This is a test.

```

**Comment by raghur** [comment]
Remove the filters line and try.

**Comment by qijianjun** [comment]
It works now, thanks!
