### ISSUE TITLE
TypeError: datetime.datetime(2018, 9, 1, 10, 0) is not JSON serializable

### ISSUE THREAD

**Issue by qijianjun** [raghur/easyblogger#44]
When I leave the publishDate value blank or delete the line, I get **AttributeError: 'Namespace' object has no attribute 'publishDate'** error.
Then I tried with **PublishDate: 2018-09-10T10:00:00**, but got the **JSON serializable** error.
I think the publishDate should be optional.

```
$ /C/Python34/Scripts/easyblogger file test.md
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "c:\python34\lib\site-packages\blogger\main.py", line 306, in processItem
    publishDate=args.publishDate)
  File "c:\python34\lib\site-packages\blogger\blogger.py", line 251, in post
    isDraft=isDraft)
  File "c:\python34\lib\site-packages\googleapiclient\discovery.py", line 788, in method
    actual_path_params, actual_query_params, body_value)
  File "c:\python34\lib\site-packages\googleapiclient\model.py", line 151, in request
    body_value = self.serialize(body_value)
  File "c:\python34\lib\site-packages\googleapiclient\model.py", line 260, in serialize
    return json.dumps(body_value)
  File "c:\python34\lib\json\__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "c:\python34\lib\json\encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\python34\lib\json\encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "c:\python34\lib\json\encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 9, 1, 10, 0) is not JSON serializable
2018-09-08T12:39:10Z <Greenlet "Greenlet-0" at 0x55fa948: processItem(Namespace(blogid='6588907483021620031', clientid=', <blogger.blogger.ContentArgParser object at 0x0000)> failed with TypeError
```

**Comment by raghur** [comment]
once again, can you post test.md?

**Comment by qijianjun** [comment]
```
<!--
id:
title    : TEST
labels   : [tag1, tag2, tag3]
format   : markdown
published: false
PublishDate: 2018-09-10T10:00:00
-->
## Title
This is a test.

```

**Comment by raghur** [comment]
Ok - I have pushed v3.1.1 to pypi. Please upgrade and and test.

**Comment by qijianjun** [comment]
It works now, thanks!
