### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte

### ISSUE THREAD

**Issue by qijianjun** [raghur/easyblogger#46]
I use python3 and test a file contains Chinese character, and got Unicode decode error. I update main.py line 368, 
from
`            with open(f, "r", newline="\n") as fh:`
to
`            with codecs.open(f, "r", "utf-8") as fh:`
it works, but the src file got messed.

**error log:**
```
$ /C/Python34/Scripts/easyblogger.exe file test.md
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\easyblogger.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\blogger\main.py", line 291, in main
    return runner(args)
  File "c:\python34\lib\site-packages\blogger\main.py", line 371, in runner
    contentArgs.updateArgs(argsCopy)
  File "c:\python34\lib\site-packages\blogger\blogger.py", line 412, in updateArgs
    self._inferArgsFromContent()
  File "c:\python34\lib\site-packages\blogger\blogger.py", line 332, in _inferArgsFromContent
    fileContent = self.theFile.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 71: illegal multibyte sequence
```

**src file**
```
<!--
PublishDate: 2018-09-10 10:00:00
format: markdown
labels: [标签1, 标签2, 标签3]
published: false
title: TEST

-->

## 标题
这是一个测试文本。

```

**messed file:**
```
<!--
PublishDate: 2018-09-10 10:00:00
format: markdown
id: '187016465340238250'
labels: ["\u6807\u7B7E1", "\u6807\u7B7E2", "\u6807\u7B7E3"]
published: false
title: TEST

-->

## ???
??һ?????ı???

```

**Comment by raghur** [comment]
pushed 3.1.2 to PyPI
