### ISSUE TITLE
ValueError: do_handshake_on_connect with python2.7

### ISSUE THREAD

**Issue by qijianjun** [raghur/easyblogger#47]
With python2 on windows, I met with this error, and don't know whether it is related to my environment settings, no same error for python3.

After comment out the two lines below, it works:
```
from gevent import monkey
monkey.patch_all()
```

Error log:
```
$ /C/Python27/Scripts/easyblogger file test.md
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "c:\python27\lib\site-packages\blogger\main.py", line 306, in processItem
    publishDate=args.publishDate)
  File "c:\python27\lib\site-packages\blogger\blogger.py", line 242, in post
    service = self._OAuth_Authenticate()
  File "c:\python27\lib\site-packages\blogger\blogger.py", line 129, in _OAuth_Authenticate
    self.service = build('blogger', 'v3', http=http, cache_discovery=False)
  File "c:\python27\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\python27\lib\site-packages\googleapiclient\discovery.py", line 222, in build
    requested_url, discovery_http, cache_discovery, cache)
  File "c:\python27\lib\site-packages\googleapiclient\discovery.py", line 269, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "c:\python27\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "c:\python27\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 1694, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 1434, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 1354, in _conn_request
    conn.connect()
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 1104, in connect
    self.ssl_version, self.host)
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 97, in _ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=hostname)
  File "c:\python27\lib\site-packages\gevent\_sslgte279.py", line 68, in wrap_socket
    _context=self)
  File "c:\python27\lib\site-packages\gevent\_sslgte279.py", line 265, in __init__
    raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
ValueError: do_handshake_on_connect should not be specified for non-blocking sockets
2018-09-11T09:01:42Z <Greenlet "Greenlet-0" at 0x3837608: processItem(Namespace(blogid='6588907484021680011', clientid=', <blogger.blogger.ContentArgParser object at 0x03D0)> failed with ValueError

```

**Comment by raghur** [comment]
Stopped trying to support both py2 and py3
