### ISSUE TITLE
python2: encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by qijianjun** [raghur/easyblogger#48]
With python2.7, I met with this error, and [https://stackoverflow.com/questions/12541370/typeerror-encoding-is-an-invalid-keyword-argument-for-this-function/13867190](https://stackoverflow.com/questions/12541370/typeerror-encoding-is-an-invalid-keyword-argument-for-this-function/13867190) say it is a known issue for python2.

```
$ /C/Python27/Scripts/easyblogger file test.md
Traceback (most recent call last):
  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "c:\python27\lib\site-packages\blogger\main.py", line 310, in processItem
    contentArgs.updateFileWithPostId(postId)
  File "c:\python27\lib\site-packages\blogger\blogger.py", line 439, in updateFileWithPostId
    with self.open(self.theFile.name, "w", encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
2018-09-11T09:15:33Z <Greenlet "Greenlet-0" at 0x4544be0: processItem(Namespace(blogid='6588907484021680011', clientid=', <blogger.blogger.ContentArgParser object at 0x0464)> failed with TypeError

```

**Comment by raghur** [comment]
Supporting both py3 and py27 is becoming harder. The fix above was for #46 - but now that breaks in py27. Frankly, I'm going to just drop py2 support altogether.
