### ISSUE TITLE
AttributeError: 'function' object has no attribute 'urlparse'

### ISSUE THREAD

**Issue by didibus** [raghur/easyblogger#5]
I get a "AttributeError: 'function' object has no attribute 'urlparse'" error when I run:

```
easyblogger get -p 4422216707770689993 -d markdown -w
```
Here's the trace:
```
Traceback (most recent call last):
  File "/usr/bin/easyblogger", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/blogger/main.py", line 241, in main
    return runner(args, blogger)
  File "/usr/lib/python3.6/site-packages/blogger/main.py", line 293, in runner
    printPosts(posts, args.fields, args.doc, args.tofiles)
  File "/usr/lib/python3.6/site-packages/blogger/main.py", line 63, in printPosts
    filename = getFilenameFromPostUrl(item['url'], docFormat)
  File "/usr/lib/python3.6/site-packages/blogger/main.py", line 30, in getFilenameFromPostUrl
    urlp = urlparse.urlparse(url)
AttributeError: 'function' object has no attribute 'urlparse'
```

**Comment by raghur** [comment]
what version of python are you using?
