### ISSUE TITLE
Missing required parameter "url"

### ISSUE THREAD

**Issue by cameronstewart** [raghur/easyblogger#8]
Hi there,

When running the code I get this error in Python 3.  Any ideas

C:\Users\info>easyblogger  get -p 1408841626968231578 -f "id,title,url,labels"
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\easyblogger.exe\__main__.py", line 9, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\blogger\main.py", line 246, in main
    return runner(args)
  File "c:\programdata\miniconda3\lib\site-packages\blogger\main.py", line 328, in runner
    return processItem(args)
  File "c:\programdata\miniconda3\lib\site-packages\blogger\main.py", line 299, in processItem
    for item in posts]
  File "c:\programdata\miniconda3\lib\site-packages\blogger\main.py", line 297, in <listcomp>
    jobs = [gevent.spawn(printPosts,
  File "c:\programdata\miniconda3\lib\site-packages\blogger\blogger.py", line 141, in getPosts
    self._setBlog()
  File "c:\programdata\miniconda3\lib\site-packages\blogger\blogger.py", line 135, in _setBlog
    request = service.blogs().getByUrl(url=self.blogUrl)
  File "c:\programdata\miniconda3\lib\site-packages\googleapiclient\discovery.py", line 732, in method
    raise TypeError('Missing required parameter "%s"' % name)
TypeError: Missing required parameter "url"

C:\Users\info>

**Comment by raghur** [comment]
that looks like the blogid is not being specified.. Can you check if this works:

`easyblogger --blogid <yourblogid> get`

If that works, then it means that you don't have a `.easyblogger` file which specifies a blog id in your %USERPROFILE% folder.

**Comment by cameronstewart** [comment]
Yes, the
easyblogger --blogid <yourblogid> get

just not for the post commands.

Can I just create the file in the %USERPROFILE% dir ?  If so what format?

Will recheck admin settings on install.

**Comment by raghur** [comment]
Please see README - it has the instructions and format. --blogid is required for every call so that easyblogger knows which blog you'd like to operate on.

**Comment by cameronstewart** [comment]
If you look at my CMD line dump...I had a blog id in that so I don't think that's the problem. 

In my user profile I can only find an 

.easyblogger.crenditials 

That file stores the oAuth...should there be another file.  I am thinking it might have something to do with admin privileges on the computer I am using

**Comment by raghur** [comment]
>easyblogger get -p 1408841626968231578 -f "id,title,url,labels"

There's no blog id in that one...

The README has instructions - https://github.com/raghur/easyblogger#default-args-file
